ocean-ds/ocean-android

app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemActivity.kt
app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemViewModel.kt
ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterTransactionListItem.kt
ocean-components/src/main/java/br/com/useblu/oceands/core/Extensions.kt
ocean-components/src/main/res/layout/ocean_transaction_list_item.xml

This reverts commit 6225a126e6411a773f4b1e24be2df6f8323c9983.
The animation for show/hiding checkbox is cancelled when it's used within a Recycler View and it is scrolled and the item is not visible anymore.
With the animation cancellation, the layout have weird behaviors like text shifted without any checkbox visible.

fix: revert"feat: added animation for transaction list item selection mode (#166)"

---

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterTransactionListItem.kt

When clicking directly on checkbox layout, the click isn't handled properly and it causes a bug.
This directly click doesn't trigger the correct callbacks and the selection the hide/show checkbox layout wasn't working properly.
Clicking directly on checkbox layout after all checkbox has been shown.

fix(transaction_list): transaction list item unhandled click on checkbox

---

app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemActivity.kt
app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemViewModel.kt
app/src/main/res/layout/activity_transaction_list_item.xml
ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterTransactionListItem.kt

When going off from selection mode, the change on checkbox was triggering the callbacks.
Clicking button on the `MainActivity` to set selection mode to false.

fix: going to selection mode false on transaction list item trigger callbacks

---

app/src/main/java/br/com/useblu/oceands/client/ui/chips/ChipsActivity.kt
app/src/main/java/br/com/useblu/oceands/client/ui/chips/ChipsViewModel.kt
app/src/main/res/layout/activity_chips.xml
ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanChipListAdapter.kt
ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterChip.kt
ocean-components/src/main/res/layout/ocean_chip_list.xml
ocean-components/src/main/res/layout/ocean_chip_list_item.xml

Transform chips parameter from ocean chips list a livedata. It will enable to change the chips after the component were created.
Opening the `MainActivity` and going to option `Chips`. A value is post on the livedata after 3 seconds and a new row with the posted item will appear.

feat: make chips parameter a live data on ocean chips list

---

ocean-components/src/main/java/br/com/useblu/oceands/utils/ExtensionsIcons.kt

- The Consult Outline icon was in the project, but was not in the Extensions file.
- The Search Solid icon was pointing to the Circle Seach Outline icon

fix: consultoutline added to extension file and fix searchsolid icons

---

ocean-components/src/main/res/layout/ocean_text_list_item.xml

The default image for the right icon had a typo: 
After the fix:

fix: typo on default icon for text list item

---

ocean-components/src/main/res/layout/item_shortcuts_adapter_ocean.xml

OceanShortcutItem's badge was showing always

fix: fix ocean shortcut badge showing always

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextListItem.kt

- Adjusting exhibition of the divider to show only when text list is not selectable.
- Manually 
<table>
<tr>
</td>
</tr>
</table>

fix: adjusting divider exhibition when text list is selectable

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanButton.kt
settings.gradle.kts

Using compose ProgressIndicator crashes the app since last compose BOM version.
Waiting for Google to release a new version fixing the issue
https://stackoverflow.com/a/77885753

fix: downgrade compose version so ProgressIndicator does not crash

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt

When using Horizontal orientation for OceanBottomSheet, the positive action button was on the left. The expected is for it to be on the right.
Horizontal orientation:
Vertical orientation:

fix: bottom sheets buttons order on horizontal orientation

---

ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/stringmask/OceanInputType.kt
ocean-components/src/test/java/br/com/useblu/oceands/ui/compose/input/OceanTextInputTest.kt

- CEP input was not sanitizing before sending the text to the callback event
- Date input had 10 numbers of max length, instead of 8

fix: apply max length correctly and add test

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTag.kt

Essa PR adiciona o ícone na tag.
Esse comportamento estava correto no componente em XML, porém no componente em compose precisou desse ajuste
Antes
Depois

Feat: add icon in tag

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextListItem.kt

- Changing vertical padding of the component to meet measurements stablished on Figma [hand-off](https://www.figma.com/design/PgLv9k22CHHZZ867HwN65y/%F0%9F%8C%8A-Ocean-DS-Core?node-id=9081-75665&m=dev)
<table>
  <tr>
         <img width="200" alt="Screenshot" src="https://github.com/user-attachments/assets/545c3ce6-eb8d-4518-935a-49514c75c6e7">
    </td>
  </tr>
</table>

fix: adjusting vertical padding

---

.github/workflows/baselineprofile.yml
baselineprofile/build.gradle.kts
gradle/libs.versions.toml
ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindAdapterBadge.kt
ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBadge.kt
ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanShortcut.kt
ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTag.kt
ocean-components/src/main/java/br/com/useblu/oceands/model/OceanBadgeType.kt

- Adds OceanTag parameter to OceanShortcut
- Fixes OceanTag spacings:
Before:
After:

feat: add OceanTag to OceanShortcut

---

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt
ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt

Changes bottom sheet error code to string

feat: change bottom sheet error code to string

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt

feat: add font size ocean inverted item when bold

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanContentList.kt
ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSettingsListItem.kt

Essa PR adiciona o estilo Strikethrough no OceanSettingsListItem
Link do Figma:
https://www.figma.com/design/PgLv9k22CHHZZ867HwN65y/%F0%9F%8C%8A-Ocean-DS-Core?node-id=19347-74478&t=v3xVPpSzRrReLakY-4

Add style Strikethrough in OceanSettingsListItem

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/expandabletextlisticonitem/OceanExpandableTextListIconItem.kt
ocean-components/src/main/java/br/com/useblu/oceands/components/compose/expandabletextlisticonitem/model/OceanExpandableTextListIconItemChild.kt

Spacing definitions is different of standard of another List Items components:
In this way, this will fix to make Expandable List Item with same spacings as another List Items to keep same experience.
Fix colors for tint icons
Actual:
Reference:
App example:
https://github.com/user-attachments/assets/d265b4e4-70e4-4d75-a436-2d7a2534909f

Fix: Expandable List Item spacings like anothers list items components

---

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomNavigation.kt
ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTopBarInverse.kt
ocean-components/src/main/java/br/com/useblu/oceands/model/compose/bottomnavigation/OceanBottomNavigationSpacingStyle.kt

CenterVertically in OceanTopBar
Extra: fix legacy bottom navigation item height
Extra: correção do bottomnavigation legado para não quebrar linha

Fix: adjust topbar alignment

---

ocean-components/src/main/java/br/com/useblu/oceands/extensions/Extensions.kt

- \u00A0 é o código Unicode para Non-Breaking Space (espaço não-quebrável)
- Isso garante que "R$" e o valor sempre fiquem juntos na mesma linha
- O texto pode quebrar em outros pontos, mas nunca vai separar a moeda do valor
Exemplo: Se houver quebra de linha, ela vai acontecer antes do "R$ 1.234,56" inteiro, mantendo a moeda e o valor sempre unidos!

feat: Replace simple space per Non-Breaking Space (\u00A0)
