ocean-ds/ocean-android

.github/workflows/ci.yml
Closes #51 
- https://github.com/ocean-ds/ocean-web/blob/master/.github/workflows/ci.yml
- https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
- https://ncorti.com/blog/howto-github-actions-building-android
- https://www.coletiv.com/blog/android-github-actions-setup/
- https://about.codecov.io/blog/code-coverage-for-android-development-using-kotlin-jacoco-github-actions-and-codecov/
- https://ryanharrison.co.uk/2020/04/12/kotlin-java-ci-with-github-actions.html
- https://github.com/DanielMartinus/Konfetti/blob/main/.github/workflows/ci-konfetti.yaml
- https://medium.com/cirruslabs/http-caching-for-github-actions-f06c2e4e22e8
- https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/.github/workflows/build.yml
=> ci: add continuous integration via gh actions

README.md
=> docs(github): improve readme

.github/CONTRIBUTING.md
=> docs(github): add contribuition guide

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/toobar/TopbarActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/toobar/TopbarViewModel.kt, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_topbar.xml, ocean-components/src/main/res/layout/ocean_top_bar.xml, ocean-components/src/main/res/layout/ocean_top_bar_complementary.xml, ocean-components/src/main/res/layout/ocean_top_bar_inverse.xml
`<include
android:id="@+id/topbar_primary"
layout="@layout/ocean_top_bar_inverse"
app:title="@{@string/title}" />`
=> feat: add topbar components

.github/workflows/cd.yml
=> fix(ci): fix adjust pipeline cd

.github/workflows/cd.yml
=> fix(ci): incriment version

ocean-components/src/main/res/drawable/icon_back_white.xml, ocean-components/src/main/res/drawable/ocean_switch_track_off.xml, ocean-components/src/main/res/drawable/ocean_switch_track_on.xml, ocean-components/src/main/res/layout/ocean_top_bar_complementary.xml, ocean-components/src/main/res/layout/ocean_top_bar_inverse.xml, ocean-tokens/src/main/res/values/tokens.xml
Adjust token space font and adjust icon topbar
=> fix: adjust token space font and adjust icon topbar

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/listitem/ListItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/listitem/ListItemViewModel.kt, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_list_item.xml, app/src/main/res/values/strings.xml, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterTextView.kt, ocean-components/src/main/res/layout/ocean_text_list_item_inverted.xml
Add new compoenent text list item inverter and sample used
=> feat: add new component text list item inverted

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapters.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/Extensions.kt, ocean-components/src/main/res/layout/ocean_text_list_item.xml, ocean-components/src/main/res/layout/ocean_text_list_item_inverted.xml
Fix margin start icon in text item list
=> fix: adjust margin start with icon

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/java/br/com/useblu/oceands/OceanBottomListSheet.kt, ocean-components/src/main/res/layout/ocean_bottom_list_sheet.xml, ocean-components/src/main/res/layout/ocean_bottom_list_sheet_item.xml
Implement a new bottom sheet that contains a list of items for the user to select.
Implement a new bottom sheet that contains a list of items for the user to select.
The new bottom sheet takes a list of strings and a title as parameters.
=> feat: implement new bottom sheet with item select

app/src/main/java/br/com/useblu/oceands/client/ui/input/InputActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/input/InputViewModel.kt, app/src/main/res/layout/activity_input.xml, ocean-components/src/main/java/br/com/useblu/oceands/OceanBottomListSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterSpinner.kt, ocean-components/src/main/res/layout/ocean_bottom_list_sheet.xml, ocean-components/src/main/res/layout/ocean_bottom_list_sheet_item.xml, ocean-components/src/main/res/layout/ocean_dropdown_menu.xml
Adapt bottom sheet select to spinner component
https://user-images.githubusercontent.com/81174887/123682854-f0c69a80-d821-11eb-8180-e431acb8f57c.mov
=> feat: adapt bottom sheet with item select at spinner

app/src/main/java/br/com/useblu/oceands/client/ui/input/InputViewModel.kt, app/src/main/res/layout/activity_input.xml, ocean-components/src/main/res/layout/ocean_input_text_field_with_icon.xml
Implements icon in input text field
=> feat: add icon in input text field

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterSpinner.kt
Fix spinner with bottom sheet behavior
Fix spinner with bottom sheet behavior
=> fix: fix bottom sheet spinner

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/java/br/com/useblu/oceands/OceanBottomListSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterSpinner.kt, ocean-components/src/main/res/layout/ocean_bottom_list_sheet_with_icon_item.xml
feat implement ocean bottom sheet with icon and description
feat implement ocean bottom sheet with icon and description
=> feat: implement ocean bottom sheet with icon and description

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeViewModel.kt, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_list_item.xml, ocean-components/build.gradle, ocean-components/src/main/java/br/com/useblu/oceands/OceanBottomListSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/OceanSearchDialog.kt, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanBottomListSheetAdapter.kt, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanBottomListSheetWithIconAdapter.kt, ocean-components/src/main/res/anim/slide_down.xml, ocean-components/src/main/res/anim/slide_up.xml, ocean-components/src/main/res/drawable/icon_clear.xml, ocean-components/src/main/res/drawable/icon_close.xml, ocean-components/src/main/res/drawable/icon_search.xml, ocean-components/src/main/res/layout/ocean_dialog.xml, ocean-components/src/main/res/layout/ocean_text_list_item.xml, ocean-components/src/main/res/layout/ocean_text_list_item_inverted.xml, ocean-components/src/main/res/values/missing_tokens.xml, ocean-components/src/main/res/values/ocean_dialog_styles.xml
=> feat: add search view

app/src/main/res/layout/activity_input.xml, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterSpinner.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/Extensions.kt, ocean-components/src/main/res/layout/ocean_dropdown_menu.xml
Add bottom sheet biding adapter
=> feat: add biding adapter

ocean-components/src/main/res/layout/ocean_dialog.xml, ocean-components/src/main/res/values/ocean_styles.xml
style: color title search view
=> style: modifier style text toolbar search view

app/src/main/res/layout/activity_buttons.xml, ocean-components/src/main/res/drawable/ocean_button_primary_critical.xml, ocean-components/src/main/res/drawable/ocean_button_primary_critical_default.xml, ocean-components/src/main/res/drawable/ocean_button_primary_critical_disabled.xml, ocean-components/src/main/res/drawable/ocean_button_primary_critical_focused.xml, ocean-components/src/main/res/drawable/ocean_button_primary_critical_hover.xml, ocean-components/src/main/res/drawable/ocean_button_primary_critical_pressed.xml, ocean-components/src/main/res/layout/ocean_button_primary_critical_lg.xml, ocean-components/src/main/res/layout/ocean_button_primary_critical_md.xml, ocean-components/src/main/res/layout/ocean_button_primary_critical_sm.xml, ocean-components/src/main/res/values/ocean_styles.xml
Add implementation primary button critical 
=> feat: implements buttons primary critical

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/buttons/ButtonsViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/radio/RadioActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/radio/RadiosViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/switchs/SwitchsActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/switchs/SwitchsViewModel.kt, app/src/main/res/layout/activity_buttons.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_radios.xml, app/src/main/res/layout/activity_switchs.xml, ocean-components/src/main/res/drawable/icon_radio_button_disabled.xml, ocean-components/src/main/res/drawable/icon_radio_button_inactive.xml, ocean-components/src/main/res/drawable/ocean_switch_track_off.xml, ocean-components/src/main/res/drawable/ocean_switch_track_on.xml, ocean-components/src/main/res/layout/ocean_switch.xml, ocean-components/src/main/res/values/missing_tokens.xml, ocean-components/src/main/res/values/ocean_styles.xml
Adjusts tokens and organize components, and adjust space into texts
=> fix: adjust tokens and alphabetic order

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapters.kt, ocean-components/src/main/res/layout/ocean_alert.xml
Adjust position icon in ocean alert
=> feat: adjust position icon

ocean-components/src/main/res/layout/ocean_balance.xml
=> fix: adjust height component

ocean-components/src/main/res/layout/ocean_balance.xml
=> fix: adjust background color

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterCardOptions.kt, ocean-components/src/main/res/color/ocean_card_text_color.xml, ocean-components/src/main/res/values/ocean_styles.xml
Adjust colors ocean card options
=> fix: adjust color

ocean-components/src/main/java/br/com/useblu/oceands/OceanTooltip.kt
=> fix: set font ocean tooltip

app/src/main/res/layout/activity_subheader.xml, ocean-components/src/main/res/layout/ocean_list_subheader.xml
=> fix: add icon to list subheader

ocean-components/src/main/res/layout/ocean_dropdown_menu.xml
Add merge layout to ocean dropdown menu.
=> fix: add merge layout to ocean dropdown menu

app/src/main/java/br/com/useblu/oceands/client/ui/input/InputActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/input/InputViewModel.kt, app/src/main/res/layout/activity_input.xml, ocean-components/src/main/java/br/com/useblu/oceands/core/BindAdapterBalance.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/BindAdapterInputToken.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapters.kt, ocean-components/src/main/res/drawable/cursor_background.xml, ocean-components/src/main/res/layout/ocean_input_token.xml, ocean-components/src/main/res/values/strings.xml
implements ocean input token and bind adapters
Reference [jira](https://useblu.atlassian.net/browse/APP-1666)
Use the sample app so you can run the tests
https://user-images.githubusercontent.com/10865241/142052075-ee7731ae-db25-467d-a405-5d772f262780.mp4
=> feat: implements ocean input token 

ocean-components/src/main/res/layout/ocean_input_text_area.xml, ocean-components/src/main/res/layout/ocean_input_text_area_numeric.xml, ocean-components/src/main/res/layout/ocean_input_text_field_with_icon.xml
Fix: Replace variable value to livedata
=> fix: replace variable value to livedata

app/src/main/java/br/com/useblu/oceands/client/ui/buttons/ButtonsViewModel.kt, app/src/main/res/layout/activity_buttons.xml, ocean-components/src/main/res/layout/ocean_dual_button_blocked.xml
Added possibility to dual button visibility. It's possible to define if the positive/negative button will be visible or not. If the parameter not be sent, the default value will be visible.
=> feat(buttons): dual button visibility modifier for positive and negative

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/chips/ChipsActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/chips/ChipsViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/chips/model/Chips.kt, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_chips.xml, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanChipListAdapter.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterChip.kt, ocean-components/src/main/res/drawable/ocean_chip_default.xml, ocean-components/src/main/res/drawable/ocean_chip_error.xml, ocean-components/src/main/res/drawable/ocean_chip_selected.xml, ocean-components/src/main/res/layout/ocean_chip_list.xml, ocean-components/src/main/res/layout/ocean_chip_list_item.xml
Implement chips component described [here](https://www.figma.com/file/PgLv9k22CHHZZ867HwN65y/%E2%9D%96-Ocean-DS-%2F-Core-Components?node-id=4170%3A43897).
Opening the chips option on `MainActivity`.
=> feat: Add chips component

app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemViewModel.kt, app/src/main/res/layout/activity_transaction_list_item.xml, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterTransactionListItem.kt, ocean-components/src/main/res/layout/ocean_transaction_list_item.xml
Add checkbox on transaction list item layout
Running the app and opening transaction list option on the `MainActivity`.
The last variation (Variation 5) shows the behavior added.
https://user-images.githubusercontent.com/32961113/146371527-b838b5d1-3032-41d1-b4db-e616dfadb9c9.mp4
=> feat: added checkbox on transaction list item

app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterTransactionListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/Extensions.kt, ocean-components/src/main/res/layout/ocean_transaction_list_item.xml
Add animation for show/hide `transaction_list_item` checkbox.
https://user-images.githubusercontent.com/32961113/146577746-f24c3d3e-f590-4625-a084-140f7eb93fa5.mp4
=> feat: added animation for transaction list item selection mode

.github/semantic.yml
With this configuration change, the semantic PR analyzer will allow commits and PRs with revert title.
=> chore: supports revert commits on semantic PR

ocean-components/src/main/res/layout/ocean_transaction_list_item.xml
When clicking on transaction list item and field `hasCheckbox` is true, is expected to show the checkbox.
It was not happening due to the checkbox's visibility was being controlled by a `MutableLiveData` and the app field `ocean_visible_or_gone` was expecting a `Boolean`
=> fix: transaction list item not showing checkbox when clicked

ocean-components/src/main/res/layout/ocean_checkbox.xml, ocean-components/src/main/res/values/ocean_styles.xml
Change checkbox's border color from default color (white) to gray.
Opening the checkbox option on `main_activity`.
=> feat(checkbox): changed checkbox's border color

app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemAdapter.kt, app/src/main/java/br/com/useblu/oceands/client/ui/transactionlistitem/TransactionListItemViewModel.kt, app/src/main/res/layout/activity_transaction_list_item.xml, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterTransactionListItem.kt, ocean-components/src/main/res/layout/ocean_transaction_list_item.xml
When clicking on `transaction_list_item` within a `RecyclerView`, strange behaviors are happening. This PR fix that.
A `RecyclerView` was added on activity for testing.
Rendering a `RecyclerView` on the activity ant interacting with him.
=> fix: ocean_transaction_list_item didn't change when it's within a recycler view

app/src/main/java/br/com/useblu/oceands/client/ui/chips/ChipsViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanChipListAdapter.kt, ocean-components/src/main/res/layout/ocean_chip_list_item.xml
Change horizontal padding ocean chips and set fixed height.
On `main_activity`.
=> feat(chips): visual adjusts on chips

.github/workflows/cd.yml
Generate tag on Github on `cdyml`.
=> feat(chore): create tag on cd.yml

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/java/br/com/useblu/oceands/OceanSnackBar.kt
=> feat: add action in snackbar

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterSpinner.kt
=> fix: add notifySetDataChanged on adapter from dropdown menu

app/src/main/java/br/com/useblu/oceands/client/ui/listitem/ListItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/listitem/ListItemViewModel.kt, app/src/main/res/layout/activity_list_item.xml, ocean-components/src/main/res/layout/ocean_text_list_item.xml
Put a clickable link at right of the `ocean_text_list_item`
Opening `List Items` option at `MainActivity` and clicking at link. The expected result is to show the `itemId` through a observe at a livedata.
=> feat: added a clickable link on right of text list item

app/src/main/res/layout/activity_list_item.xml, ocean-components/src/main/res/layout/ocean_text_list_item.xml
Added single line option for text list item. It will truncate the text and add a three dot on the end.
Opening the `MainActivity` and going to `List Items`, where is shown a item with a long title which is truncated.
=> feat: added single line option for text list item

app/src/main/java/br/com/useblu/oceands/client/ui/listitem/ListItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/listitem/ListItemViewModel.kt, app/src/main/res/layout/activity_list_item.xml, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapters.kt, ocean-components/src/main/res/layout/ocean_text_list_item.xml
=> feat: add long click pressed in view

app/src/main/res/layout/activity_transaction_list_item.xml, ocean-components/src/main/res/layout/ocean_transaction_list_item.xml
Added support to receive a tag type on transaction_list_item
Opening `MainActivity` and going to `Transaction List` option. There will be a `transaction_list_item` with custom tag type.
=> feat: added tag type on transaction_list_item

app/src/main/res/layout/activity_transaction_list_item.xml, ocean-components/src/main/res/layout/ocean_transaction_list_item.xml
Added an option to hide tag icon on `transaction_list_item`. The default value is false.
Opening `MainActivity` and going to `Transaction List` option. There will be a `transaction_list_item` with a no icon tag.
=> feat: added option to hide tag icon on transaction list item

app/src/main/res/layout/activity_description.xml, ocean-components/src/main/res/layout/ocean_description.xml
Component `ocean_description` now supports receive a text color by parameter.
Opening the `MainActivity`, going to `Typograph` and `Description` and checking the `ocean_description` component with a different text color.
=> feat: textColor parameterizable on description

app/src/main/res/layout/activity_input.xml, ocean-components/src/main/res/layout/ocean_input_text_search.xml
Add place holder in ocean input text search
=> feat: add place holder in ocean search

ocean-components/src/main/res/layout/ocean_checkbox.xml, ocean-components/src/main/res/layout/ocean_transaction_list_item.xml, ocean-components/src/main/res/xml/ocean_transaction_list_item_xml_constraintlayout_scene.xml
Fixed checkbox cropping at left on transaction_list_item
Opening `MainActivity` and clicking o `Transaction List` option. On click at a item which has checkbox, it will enter on selection mode and show the checkbox.
=> fix: checkbox cropping at left on transaction_list_item

app/src/main/res/layout/activity_input.xml, ocean-components/src/main/res/layout/ocean_input_text_area.xml, ocean-components/src/main/res/layout/ocean_input_text_area_numeric.xml, ocean-components/src/main/res/layout/ocean_input_text_field_with_icon.xml
Implementaçao da opcao de disabilitar os componentes ocean input text
=> feat: add option disabled input text

app/src/main/java/br/com/useblu/oceands/client/ui/input/InputActivity.kt, app/src/main/res/layout/activity_input.xml, ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapters.kt, ocean-components/src/main/res/drawable/icon_eye_off.xml, ocean-components/src/main/res/drawable/icon_eye_on.xml
Update icon eye and color designer system
=> Feat: update icon eye

ocean-components/src/main/res/layout/ocean_input_text_search.xml
Added a ellipsize attribute to elegantly truncate text hint that is too large to be viewed on search input
A manual test done by checking if the new feature are being shown as expected.
=> feat: ellipsize on input search added

app/src/main/res/layout/activity_input.xml, ocean-components/src/main/res/layout/ocean_input_text_field_with_icon.xml
Add loading view in ocean_input_text_field_with_icon
=> feat: add loading in ocean_input_text_field_with_icon

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterSpinner.kt, ocean-components/src/main/res/layout/ocean_dropdown_menu.xml
=> feat: add disable param to spinner

ocean-components/src/main/res/layout/ocean_checkbox.xml, ocean-components/src/main/res/layout/ocean_text_list_item_inverted.xml
Add bold in text to list_item_inverted and adjust text error margin checkbox
=> fix: adjust text checkbox and list

app/src/main/java/br/com/useblu/oceands/client/ui/tab/TabViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/BindAdapterRecyclerView.kt, ocean-components/src/main/res/layout/ocean_tab.xml, ocean-components/src/main/res/layout/ocean_text_list_item.xml
Change list type to entries from ocean_tab
=> fix: adjust list type for entries ocean_tab

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterSwitch.kt, ocean-components/src/main/res/layout/ocean_switch.xml
Refactor binding adapter ocean switch
=> feat: refactor binding adapter

app/src/main/res/layout/activity_list_item.xml, ocean-components/src/main/res/layout/ocean_text_list_item.xml
=> fix: adjust image url parameter

ocean-components/src/main/res/layout/ocean_checkbox.xml, ocean-components/src/main/res/layout/ocean_text_list_item.xml
Adjust spaces  ocean text list item
=> feat: adjust spaces

app/src/main/java/br/com/useblu/oceands/client/ui/buttons/ButtonsViewModel.kt, app/src/main/res/layout/activity_buttons.xml, app/src/main/res/menu/toggle_type.xml, ocean-components/src/main/res/color/ocean_button_secondary_critical_text_color.xml, ocean-components/src/main/res/drawable/ocean_button_secondary_critical.xml, ocean-components/src/main/res/drawable/ocean_button_secondary_critical_default.xml, ocean-components/src/main/res/layout/ocean_button_secondary_critical_lg.xml, ocean-components/src/main/res/layout/ocean_button_secondary_critical_md.xml, ocean-components/src/main/res/layout/ocean_button_secondary_critical_sm.xml, ocean-components/src/main/res/values/ocean_styles.xml
Implements ocean secondary critical button
=> feat: implements ocean secondary critical button

ocean-components/src/main/java/br/com/useblu/oceands/core/BindingAdapterCardOptions.kt, ocean-components/src/main/res/layout/item_option_card_adapter_ocean.xml
Fix color selected ocean card option
=> style: fix color selected ocean card option

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/crosscellcard/CardCrossCellActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/crosscellcard/CardCrossCellViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_card_cross_cell.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/values/strings.xml, ocean-components/src/main/res/drawable/icon_chevron_right_brand_primary.xml, ocean-components/src/main/res/drawable/ocean_cross_cell_card.xml, ocean-components/src/main/res/layout/ocean_cross_sell_card.xml, ocean-components/src/main/res/layout/ocean_text_list_item.xml
=> feat: implements card cross cell

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/build.gradle, ocean-components/src/main/java/br/com/useblu/oceands/OceanDatePickerFullscreen.kt, ocean-components/src/main/java/br/com/useblu/oceands/core/DisabledDaysDecorator.kt, ocean-components/src/main/res/layout/ocean_date_picker_fullscreen.xml
Implementada a validação para desabilitar datas no componente de calendário.
CDCCORE 202
=> feat: validation to disable dates

app/src/main/res/drawable/sample_background_cross_sell_card.xml, app/src/main/res/layout/activity_card_cross_sell.xml, ocean-components/src/main/res/layout/ocean_cross_sell_card.xml
Modification of card cross sell component to accept gradient or solid color
[APP-2513](https://useblu.atlassian.net/jira/software/c/projects/APP/boards/72?modal=detail&selectedIssue=APP-2513)
Manually tested.
=> feat: validates how the card cross sell component accepts gradient or solid color

app/src/main/res/layout/activity_headings.xml, ocean-components/src/main/res/layout/ocean_heading_1.xml, ocean-components/src/main/res/layout/ocean_heading_2.xml, ocean-components/src/main/res/layout/ocean_heading_3.xml, ocean-components/src/main/res/layout/ocean_heading_4.xml, ocean-components/src/main/res/layout/ocean_heading_5.xml, ocean-components/src/main/res/layout/ocean_heading_5_inverse.xml, ocean-components/src/main/res/values/ocean_styles.xml, ocean-components/src/main/res/values/ocean_styles_inverse.xml
Create a new Heading 5 component and change the default colors of headings as per Figma.
[## Types of changes](https://useblu.atlassian.net/jira/software/c/projects/APP/boards/72?modal=detail&selectedIssue=APP-2525)
=> New typography component Heading 5

ocean-components/src/main/res/layout/ocean_cross_sell_card.xml
Create color parameters for cross sell title and subtitle.
=> feat: create color parameters for cross sell title and subtitle

app/src/main/java/br/com/useblu/oceands/client/ui/shortcuts/ShortcutsActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/shortcuts/ShortcutsViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanShortcutsListAdapter.kt, ocean-components/src/main/res/layout/item_shortcuts_adapter_ocean.xml, ocean-components/src/main/res/layout/item_shortcuts_highlight_adapter_ocean.xml
Adjust shortcut size and change type of icon variable.
Fixes # ([issue](https://useblu.atlassian.net/browse/APP-2529))
=> feat: adjust shortcut size and change type of icon variable

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/carditem/CardItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/carditem/CardItemViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_card_item.xml, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/res/drawable/ocean_card_item_background.xml, ocean-components/src/main/res/layout/ocean_card_item.xml
Simple component that looks like CardGroup but its only one item and have some layout changes.
Rounded background, textSize, colors and option to hide the arrow at right.
app:title
app:subtitle
app:caption
app:icon
app:iconUrl
app:arrow
=> feat: card list item

app/src/main/res/layout/activity_card_group.xml, dependencies.gradle, ocean-components/src/main/res/layout/ocean_card_group.xml
Adding component Group-CTA to CardGroup and adjusting subtitle to be adaptable to long texts.
Manually tested.
<table>
<tr>
<td style="padding:10px">   
</td>
</tr>
</table>
=> Adjusting CardGroup layout

app/src/main/java/br/com/useblu/oceands/client/ui/carditem/CardItemViewModel.kt
=> Force to generate version

ocean-components/src/main/res/layout/ocean_tab.xml
Adding id name on view element
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update
Manually tested.
=> feat:adding id name to the tab recycleview

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/orderedlistitem/OrderedListItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/orderedlistitem/OrderedListViewModel.kt, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_ordered_list.xml, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanOrderedListAdapter.kt, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterOrderedListItem.kt, ocean-components/src/main/res/drawable/ocean_number_ordered_list_item.xml, ocean-components/src/main/res/layout/ocean_ordered_list.xml, ocean-components/src/main/res/layout/ocean_ordered_list_item.xml
=> feat: ordered list

app/src/main/java/br/com/useblu/oceands/client/ui/shortcuts/ShortcutsViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanShortcutItem.kt, ocean-components/src/main/res/layout/item_shortcuts_adapter_ocean.xml
Update Shortcut Icon color to blue
=> feat: update shortcut icon color to blue

app/src/main/res/layout/activity_settings_list_item.xml, app/src/main/res/values/strings.xml, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanSettingsStatus.kt, ocean-components/src/main/res/layout/ocean_settings_list_item.xml, ocean-components/src/main/res/layout/ocean_tag.xml
Implements adjusts component ocean settings 
=> feat: implements adjusts in ocean settings list item

app/src/main/java/br/com/useblu/oceands/client/ui/optionscard/OptionsCardViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapters.kt, ocean-components/src/main/res/layout/item_option_card_adapter_ocean.xml, ocean-components/src/main/res/layout/item_option_card_disabled_adapter_ocean.xml
- update Options Card layout to match Figma design
- add binding adapters (
- setLayoutMarginStart: set layout margin start with data binding
- setTintColor: set ImageView tint color with the color resource id (when ContextCompat.getColor is needed)
- setTint: set ImageView tint color (when ContextCompat.getColor is NOT needed)
=> feat: update Options Card component and add binding adapters

app/src/main/res/layout/activity_status_list_item.xml, ocean-components/src/main/res/color/ocean_list_item_hover.xml, ocean-components/src/main/res/drawable/ocean_list_item_hover.xml, ocean-components/src/main/res/layout/ocean_status_list_item.xml, ocean-components/src/main/res/layout/ocean_text_list_item_base.xml
- Moving selector xml to drawable folder
- Updating dependencies
- Removing unnecessary dependencies from projects that import ocean-components
=> Fix crash using resource color with selector

ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindAdapterTag.kt, ocean-components/src/main/res/layout/ocean_tag.xml
Fix an findViewById that was not seen last PR
=> fix: binding adapter

app/src/main/res/layout/activity_status_list_item.xml, ocean-components/src/main/res/layout/ocean_status_list_item.xml
- Adds a 1 line limit to Status List Item title with ellipsize=end
=> feat: ellipsize on status list item

app/src/main/res/layout/activity_card_item.xml, app/src/main/res/layout/activity_text_link.xml, ocean-components/src/main/res/layout/ocean_card_item.xml, ocean-components/src/main/res/layout/ocean_link_text.xml, ocean-components/src/main/res/layout/ocean_link_text_inverse.xml
- Sets margin start for text if leading icon has visibility gone.
- Sets visibility gone for description is no text is passed as parameter
- Adjustments to Text Link component
=> feat: update card item margin start

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanBottomListSheet.kt, ocean-components/src/main/res/layout/ocean_bottom_list_sheet.xml
Adding a body icon to the bottom list sheet  layout that might be added when necessary. 
Manually tested
<table>
<tr>
</td>
</tr>
</table>
=> feat: adding body icon to the bottom list sheet

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanUnorderedListAdapter.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanUnorderedListItem.kt, ocean-components/src/main/res/layout/ocean_bottom_list_sheet.xml, ocean-components/src/main/res/layout/ocean_bottom_list_sheet_item.xml, ocean-components/src/main/res/layout/ocean_unordered_list_item.xml
- Adding spacers parameters control in unordered list item to add/remove margins at start/end of layout due lack of them
- Fixing layout of bottom list sheet due wrong arrangement of items in recycler view when using adapter.
Manually tested
<table>
<tr>
</td>
</td>
</tr>
</table>
=> Fix: app 3557 bottom sheet list layout

app/src/main/res/layout/activity_text_list_icon_item.xml, ocean-components/src/main/res/layout/ocean_text_list_icon_item.xml
Makes some adjustments to OceanTextListIcon component
=> feat: adjust text list icon component

ocean-components/src/main/java/br/com/useblu/oceands/utils/ExtensionsIcons.kt, ocean-tokens/src/main/res/drawable/ocean_icon_barcode_outline_highlight.xml, ocean-tokens/src/main/res/drawable/ocean_icon_qrcode_outline_highlight.xml
Adding new tokens corresponding to the new highlight icons
Manually tested
=> Feat: APP-3655 creating ocean token

ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanChipListAdapter.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanOptionsBottomListSheet.kt, ocean-components/src/main/res/layout/ocean_options_bottom_list_sheet.xml, ocean-components/src/main/res/layout/ocean_status_list_item.xml
- Add secondary button click that was missing
- Fixes button layout 
=> feat: add secondary button click action and fix buttons layout

ocean-components/src/main/java/br/com/useblu/oceands/utils/ExtensionsIcons.kt
=> fix: fix eyeoutline icon

app/src/main/java/br/com/useblu/oceands/client/ui/chips/ChipsViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanChip.kt, ocean-components/src/main/res/layout/ocean_basic_chip_item.xml
Conditional vertical divider added to chip component.
- [] Bug fix (non-breaking change which fixes an issue)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update
Manually tested
<table>
<tr>
</td>
</tr>
</table>
=> feat: adding a divider to basic chip

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/donut/DonutActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/donut/DonutViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/shortcuts/ShortcutsViewModel.kt, app/src/main/res/layout/activity_donut.xml, app/src/main/res/layout/activity_home.xml, ocean-components/build.gradle, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterDonut.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanDonutItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanDonutModel.kt, ocean-components/src/main/res/layout/ocean_donut.xml, ocean-components/src/main/res/layout/ocean_unordered_list_item.xml
Adds the Donut component:
https://github.com/ocean-ds/ocean-android/assets/15229294/e36f277d-d238-4f78-9b7d-fe53ba3f2dff
=> feat: donut component

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/progressbar/ProgressBarActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/progressbar/ProgressBarViewModel.kt, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_progress_bar.xml, ocean-components/src/main/res/drawable/custom_progress_bar.xml, ocean-components/src/main/res/layout/ocean_caption.xml, ocean-components/src/main/res/layout/ocean_progress_bar.xml
=> feat: implements ocean progress bar

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/chartcard/ChartCardActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/chartcard/ChartCardViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/donut/DonutActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/donut/DonutViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_chart_card.xml, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanChartLegendAdapter.kt, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterChartCard.kt, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterDonut.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanDonutItem.kt, ocean-components/src/main/res/drawable/circle_transparent.xml, ocean-components/src/main/res/layout/ocean_chart_card.xml, ocean-components/src/main/res/layout/ocean_chart_legend.xml, ocean-components/src/main/res/layout/ocean_description.xml
=> feat: implements ocean chart card

app/src/main/java/br/com/useblu/oceands/client/ui/headerapp/HeaderAppViewModel.kt, ocean-components/src/main/res/layout/ocean_balance_blu_card.xml, ocean-components/src/main/res/layout/ocean_balance_others_card.xml
Fix: missing function invoke on clicking buttons
=> fix: header app button actions

app/src/main/java/br/com/useblu/oceands/client/ui/chartcard/ChartCardViewModel.kt, app/src/main/java/br/com/useblu/oceands/client/ui/headerapp/HeaderAppViewModel.kt, app/src/main/res/layout/activity_chart_card.xml, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanChartLegendAdapter.kt, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterChartCard.kt, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterDonut.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanDonutItem.kt, ocean-components/src/main/res/layout/ocean_balance_blu_card.xml, ocean-components/src/main/res/layout/ocean_balance_blu_card_simple.xml, ocean-components/src/main/res/layout/ocean_balance_others_card.xml, ocean-components/src/main/res/layout/ocean_balance_others_card_simple.xml, ocean-components/src/main/res/layout/ocean_card_group.xml, ocean-components/src/main/res/layout/ocean_chart_card.xml, ocean-components/src/main/res/layout/ocean_chart_legend.xml, ocean-components/src/main/res/layout/ocean_header_app.xml
Implements hightLite ocean chart card
https://github.com/ocean-ds/ocean-android/assets/10865241/ceaf7d84-46a2-4b66-b30c-81374d551718
=> feat: implements hightlite

ocean-components/src/main/res/layout/ocean_card_group.xml
=> fix: card group id fix

ocean-components/src/main/res/layout/ocean_balance_blu_card_simple.xml, ocean-components/src/main/res/layout/ocean_balance_others_card.xml, ocean-components/src/main/res/layout/ocean_balance_others_card_simple.xml
- Margin and layout visibility fixes
=> fix: layout margin

ocean-components/src/main/res/layout/item_parent_text_list.xml, ocean-components/src/main/res/layout/ocean_balance_blu_card.xml, ocean-components/src/main/res/layout/ocean_balance_others_card.xml, ocean-components/src/main/res/layout/ocean_expandable_text_list_icon_item.xml
=> fix: header app and expandable list item margins

app/src/main/java/br/com/useblu/oceands/client/ui/shortcuts/ShortcutsViewModel.kt, app/src/main/res/layout/activity_shortcuts.xml, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterShortcuts.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanShortcutItem.kt, ocean-components/src/main/res/layout/item_shortcuts_adapter_ocean.xml, ocean-components/src/main/res/layout/ocean_shortcut_list.xml
=> feat: refactor ocean shortcuts

app/src/main/java/br/com/useblu/oceands/client/ui/bottomnavigation/BottomNavigationActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/bottomnavigation/BottomNavigationViewModel.kt, app/src/main/res/layout/activity_bottom_navigation.xml, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanBottomNavigation.kt
Adds possibility to add a single item or clear all the items.
https://github.com/ocean-ds/ocean-android/assets/15229294/281feafc-0339-4eee-9052-63f93b4fa066
=> feat: fixes

ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterTextView.kt, ocean-components/src/main/res/layout/ocean_link_text.xml
=> feat: add underline in text link

ocean-components/src/main/res/layout/ocean_status_list_item.xml
=> feat: add context menu

ocean-components/src/main/res/layout/ocean_bottom_list_sheet.xml
remove space between title and body icon 
=> Feat: remove spacing

app/build.gradle, ocean-components/build.gradle, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBadge.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTag.kt, ocean-components/src/main/res/layout/ocean_input_text_field_with_icon.xml
Creates OceanBadge and OceanTag component using compose
=> feat: create OceanBadge  and OceanTag with compose

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanButton.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextListIconItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanUnorderedListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanTextListIconItemModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanTextListIconItemModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanUnorderedListItemModel.kt
Creates compose component for TextListIconItem
=> feat: create compose component for textlisticonitem

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomNavigation.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanStatusListItem.kt
Fix optional arguments on OceanStatusListItem
=> fix: fix optional arguments for OceanStatusListItem

.github/workflows/cd.yml, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomNavigation.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanBottomNavigationModel.kt
Enhancements and adjustments to prevent unneeded processing
=> feat: enhancement and adjustment to OceanBottomNavigation

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomNavigation.kt
More adjustments to OceanBottomNavigation
=> feat: more adjustments

.github/workflows/releases.yml
Uses this Github action (https://github.com/ncipollo/release-action) to automate releases generation on every version tag created
=> feat: create releases workflow

.github/workflows/releases.yml, ocean-components/src/main/java/br/com/useblu/oceands/utils/ExtensionsIcons.kt
=> fix: fix icon x solid using x circle solid

.github/workflows/cd.yml, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSnackbar.kt
Creates compose Snackbar component.
=> feat: create snackbar component

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomNavigation.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSnackbar.kt
- Add text parameter to OceanSnackbar
- Removes debug prints inside OceanBottomNavigation
=> feat: add text parameter to snackbar and remove debug print

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/res/layout/activity_home.xml, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanBottomSheetCompose.kt, ocean-components/src/main/res/layout/ocean_bottom_sheet_compose.xml
Creates a Bottom Sheet that accepts a composable as content
=> feat: create OceanBottomSheetCompose

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanBottomSheetCompose.kt, ocean-components/src/main/res/layout/ocean_bottom_sheet_compose.xml
- BottomSheet buttons are now in compose
- withAction functions parameters now accepts only String
=> feat: refactor ocean bottom sheet compose

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanLink.kt
=> feat: create component

ocean-components/src/main/res/layout/ocean_input_text_field_with_icon.xml
- Add a new argument for OceanTextInputWithIcon to set the text color for the label
- Updates text input height to match figma
=> feat: add labelTextColor argument

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanButton.kt
Adds a conditional to check if button internal spacing should be rendered. Now it should show only if icon is not null and text if not empty
=> feat: update button spacing if text is empty

ocean-components/src/main/res/layout/item_parent_text_list.xml
=> feat: add color to image

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanStatusListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTag.kt
=> feat: add tag icon to status list item

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanUnorderedListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanUnorderedListItemModel.kt
Modification in the component so that we can stabilize the list item
=> Feat: update component OceanUnorderedListItem

ocean-components/src/main/res/layout/ocean_input_text_search.xml
Adds error string for Ocean Search Input
=> feat: add error string to input text search

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanShimmering.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanStatusListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/skeleton/OceanStatusListItemSkeleton.kt
- implementing Ocean Shimmering effect to be used on skelentons
https://github.com/ocean-ds/ocean-android/assets/38379044/a1cd34b1-6e1d-455f-8fc4-854d1af5f72e
=> feat: implementing skeleton effect

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTab.kt
OceanTab background color was not set to interface light pure
=> fix: update ocean tab background color

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanCheckbox.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanRadioButton.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSelectableBox.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSelectableRadio.kt
- Adding missing parameter for unsettled state
- Replace parameter for error message emptiness test
- Manually tested
=> fix: adding missing parameter for unsettled state

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextListItem.kt
=> feat: create inverted text list item

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTab.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanText.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTheme.kt
- Updates OceanInvertedTextListItem and creates OceanText
=> feat: create OceanText and update inverted text list item

ocean-components/src/main/java/br/com/useblu/oceands/components/OceanBottomSheetCompose.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/stringmask/OceanInputType.kt
- Adds Email type to OceanInputType
- Passes dialog context to compose so it can dismiss inside compose
=> feat: add ocean input type

buildSrc/src/main/kotlin/Configs.kt
=> fix: copilot made a mistake (and i didn't see it)

.github/dependabot.yml
=> update dependabot max PR's

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/header/OceanHeaderApp.kt
=> fix: ocean header

ocean-components/src/main/java/br/com/useblu/oceands/extensions/Extensions.kt
Adjusting ocean date formatter to make moth name first letter capital.
=> fix: correcting date formatter to insert month name first letter capitalized

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanCarousel.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanOnboarding.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanPageIndicator.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/header/OceanHeaderApp.kt, ocean-components/src/main/res/layout/ocean_carousel.xml
Creates OceanCarousel with Compose
=> feat: compose ocean carousel

ocean-components/src/main/java/br/com/useblu/oceands/extensions/Extensions.kt
- Fix regex to properly match the moth abbreviation and uppercase first letter
- Manually tested
=> fix: correcting min amount char on month regex

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanCarousel.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanCarouselItem.kt
Use correct parameter on Ocean Carousel Compose
=> feat: ocean carousel correct parameters

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanGroupCta.kt
Creates OceanGroupCta using Compose
=> feat: create ocean group cta

ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanOrderedListAdapter.kt, ocean-components/src/main/res/layout/ocean_bottom_list_sheet.xml, ocean-components/src/main/res/layout/ocean_bottom_sheet.xml
Adds gravity center to Bottom Sheet List title and caption
=> fix: add center to bottom sheet content

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanShortcut.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanBadgeType.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanTransactionListUIModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/utils/OceanIcons.kt
Adds @Immutable annotation to classes used by Compose
=> feat: Adds @immutable annotation to classes used by Compose

ocean-components/src/main/res/layout/ocean_card_item.xml
=> feat: adjust align text

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSectionHeader.kt
Creates OceanSectionHeader component
=> feat: create OceanSectionHeader

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt
Remove sheet state, migration to onDismiss
=> feat: remove sheet state

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt
Fixes images size for compose bottom sheet
=> fix: image sizes

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/utils/UiText.kt
Create UiText wrapper so we can reference string resources and only use them when required by the UI inside a compose context
=> feat: ui text wrapper so we can create bottom sheet extensions

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanOnboarding.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanOnboardingPageModel.kt
=> feat: add suport link

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanAlert.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanAlertType.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/OceanButtonColors.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/OceanButtonStyle.kt
- Implementing new style for OceanAlert to be able to perform click action
- Manually
<table>
<tr>
</td>
</tr>
</table>
=> Feat:APP-5127 adding ocean alert new style entiled short with action

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanAlert.kt
=> fix: ocean alert sizes

app/src/main/res/layout/activity_status_list_item.xml, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanStatusListItem.kt, ocean-components/src/main/res/layout/ocean_status_list_item.xml
Card Jira: 
https://useblu.atlassian.net/browse/APP-5115
=> Feat: add badge into status list item

ocean-components/src/main/java/br/com/useblu/oceands/components/OceanFilterBar.kt
- Implementing OceanFilterBar compose compoent
- Manually
<table>
<tr>
</td>
</td>
</tr>
</table>
=> Feat: creating ocean filter bar

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSettingsListItem.kt
=> feat: create OceanSettingsListItem with compose

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanTransactionListItem.kt
- Adding coloring text style for canceled values
<table>
<tr>
</td>
</tr>
</table>
=> feat: adding canceled style text coloring

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt
Adds a missing TextAlign parameters for OceanBottomSheet Texts
=> fix: add missing text align

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanButton.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/OceanButtonStyle.kt
=> feat: update ocean buttons

ocean-components/src/main/java/br/com/useblu/oceands/extensions/Extensions.kt
=> feat: truncate values before formatting with currency

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanTransactionListItem.kt
=> fix: isCancelled not being applied

app/src/main/java/br/com/useblu/oceands/client/ui/balance/BalanceViewModel.kt, app/src/main/res/layout/activity_balance.xml, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindAdapterBalance.kt, ocean-components/src/main/res/layout/ocean_balance.xml
Updates ocean_balance layout to remove the bottom section
=> feat: remove external balance info from OceanBalance xml component

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanIcon.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextInput.kt, ocean-components/src/main/java/br/com/useblu/oceands/utils/OceanIcons.kt
=> feat: add icon and iconClick to OceanTextInput

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextInput.kt
OceanInputText was not updating when the value was updated externally
=> fix: component not updating when text changes

ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/stringmask/OceanInputType.kt
Adds a Date mask for OceanTextInput
=> feat: date mask

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextInput.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/stringmask/OceanInputType.kt
=> fix: considering only digits for max length

ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/stringmask/OceanInputType.kt
Fix date mask being only visual and not changing the value
=> fix: date mask

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextInput.kt
=> feat: add support text area

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanAlert.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextInput.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanAlertType.kt
=> feat: add support alert bookmarked

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/input/OceanInputTextSearch.kt
Adds label and oceanInputType parameters to OceanTextSearchInput
=> feat: add parameter to OceanInputTextSearch

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanCalloutList.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanOrderedList.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanUnorderedList.kt
- Creates OceanOrderedList 
- Adjusts spacing for OceanUnorderedList
- UnorderedList: https://www.figma.com/file/IuhmciYoyhCv8V4NJ6NxzH/Autentica%C3%A7%C3%A3o-de-usu%C3%A1rio?type=design&node-id=2989-128342&mode=design&t=PqlAWk3eLE203lMA-4
- OrderedList: https://www.figma.com/file/3PGHdq5sgj3SyL4MAKqLLu/Boleto-Mais-Seguro?type=design&node-id=4506-82685&mode=design&t=FfoWTlkoI7wWP1xc-4
=> feat: create ocean ordered list

ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapterDonut.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/chart/OceanChartScore.kt
=> feat: implements component ocean chart score

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTag.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanTagType.kt
=> feat: adjust mapper colors

ocean-components/src/main/res/layout/ocean_bottom_sheet.xml
Ajust space image in bottom sheet
=> feat: adjust bottom sheet space image

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/input/OceanTextInput.kt
Adds a helper parameter to OceanInputText
=> feat: add helper parameter on OceanTextInput

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanTransactionListItem.kt
=> feat: add support trailed icon

app/src/main/java/br/com/useblu/oceands/client/ui/descriptorlistitem/DescriptorListItemActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/descriptorlistitem/DescriptorListViewModel.kt, app/src/main/res/layout/activity_descriptor_list.xml, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanDivider.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanDescriptorList.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/OceanColors.kt, ocean-components/src/main/res/layout/ocean_descriptor_list.xml
Creates OceanDescriptorList in compose
=> feat: creates OceanDescriptorList in compose

ocean-components/src/main/java/br/com/useblu/oceands/components/OceanFilterBar.kt
=> feat: adjust divider ocean filter bar

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanDropdownMenu.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/OceanTextStyle.kt
- This PR implements OceanDropDown compose component.
- Apply changes on OceanBottomSheet column layout
- Add new OceanTextStyles for hint and error
- Manually tested
<table>
   <tr>
     <td style="padding:10px"> 
          <img width="200" alt="Screenshot" src="https://github.com/ocean-ds/ocean-android/assets/38379044/068a39cf-fad7-459c-8889-427067338ce6">
     </td>
   </tr>
</table>
=> Feat: APP-5682 implementing ocean dropdown

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/header/OceanHeaderApp.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanHeaderAppModel.kt
add option hide blu plus header component
=> feat: add option hide blu plus

gradle/libs.versions.toml, ocean-components/build.gradle.kts, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/input/OceanTextInput.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/stringmask/CurrencyMaskVisualTransformation.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/stringmask/OceanInputType.kt, ocean-components/src/test/java/br/com/useblu/oceands/ui/compose/stringmask/CurrencyMaskVisualTransformationTest.kt
Refactors the Currency type for OceanTextInput
https://github.com/ocean-ds/ocean-android/assets/15229294/cc03b51c-c096-4b3d-87cc-b06affeec500
=> feat: OceanTextInput with Currency type

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanDescriptorList.kt
- Adjusting condition that apply color to the value field in component
- Coloring is not applied when field new value in the model is empty or blank
- Manually
=> fix: change condition for checking if it is also blank value

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanCardListItem.kt
=> feat: add support icon

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanScrollableTab.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTab.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/chart/OceanChartScore.kt
Add header and footer component
https://github.com/ocean-ds/ocean-android/assets/15229294/cb632af4-3fbf-49dc-bcb4-3c08090190e5
=> feat: add scrollable tab header and footer parameter

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanCardListItem.kt
=> feat: adjust params tag

.github/dependabot.yml, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanProgressBar.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/content/OceanCardGroup.kt
Creates OceanProgressBar and adds it to OceanCardGroup
=> Feat/compose OceanProgressBar

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanAlert.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanAlertType.kt
=> feat: add tooltip in alert

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanStatusListItem.kt
- Adjusting ocean status list item to accept nullable tag type and position since tag can be nullable.
=> Feat: update tag elements to bem nullable

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt
Implements icon in button 
Implements background color params
=> feat: add support icon in button bottomSheet + add background params

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanShortcut.kt
Fix aditional space at the end of OceanShortcut list
=> fix: adjust OceanShortcut spacing

ocean-components/src/main/res/values/missing_tokens.xml, ocean-components/src/main/res/values/tokens.xml
- Adding token to correct file
=> Fix: adding missing token on right file

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSwitch.kt
Implements ocean switch in compose
=> feat: implements ocean switch

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanButton.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanIcon.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTransactionFooter.kt
=> feat: create ocean footer in compose

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/bindingadapters/BindingAdapters.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanBottomSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt, ocean-components/src/main/res/layout/ocean_bottom_sheet.xml
Implements maxWidth and maxHeight image sheet
=> feat: implements params maxWidth and maxHeight

ocean-components/src/main/res/layout/ocean_transaction_list_item.xml
=> feat: add veriry empty value

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTopBarInverse.kt
This PR is adding a composable parameter to TopBar
=> Feat: adding a composable parameter to OceanTopBarInverse

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTransactionFooter.kt
Fix component color when newValue is blank empty
=> fix when newValue is emptyString

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextListIconItem.kt
- Adding a parameter to hide/show icon background.
=> feat: adding parameter to hide icon background

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanCardOption.kt
=> feat: create OceanCardOption

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt
Only allows compose OceanBottomSheet to dismiss on BackPress it is is dismissible
=> feat: close bottom sheet with backpress only if it is dismissible

app/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Configs.kt, gradle/libs.versions.toml, ocean-components/build.gradle.kts
=> chore: revert kotlin 2.0

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTopBarInverse.kt
- Adjusting spacings and alignment of the component
=> fix: adjusting spacings and alignment of the component

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt
Essa PR corrige a ordem de chamada das funções no botão da bottom sheet.
=> feat: fixes the order of function calls in buttons

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/res/layout/ocean_bottom_sheet.xml
Update rules for visible or gone
=> fix: remove visible or gone

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt
Add callback on dismiss user in bottom sheet
=> feat: add callback on dismiss user

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanDescriptorList.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanDescriptorListItem.kt, ocean-components/src/main/res/layout/ocean_blu_footer.xml, ocean-components/src/main/res/values/strings.xml
Fixes spacing and show label differently when model has title but not value
=> feat: update ocean descriptor list

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTag.kt
=> fix: spaces tag

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTag.kt, ocean-components/src/main/java/br/com/useblu/oceands/extensions/compose/Extensions.kt
Add support tag with text strike
=> feat: add support text strike in ocean tag

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanUnorderedList.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanUnorderedListItemModel.kt
Add support icon color and background
=> feat: add support icon color and background

ocean-components/src/main/java/br/com/useblu/oceands/utils/OceanIcons.kt
O drawable para o ícone  COINS_HAND_OUTLINE estava errado.
=> fix: drawable icon

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanBottomSheet.kt
add on dmiss callback in close dialog
=> feat: add on dismiss callback in close dialog

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/content/OceanCardGroup.kt
=> feat: add caption + type

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanContentList.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTag.kt
- Creating a tag component more flexible to assemble
- Creating content list component using the same strategy as done in tag component
<table>
  <tr>
         <img width="200" alt="Screenshot" src="https://github.com/user-attachments/assets/b87d07f0-06a9-4424-adf1-3fdc134fdaf8">
    </td>
         <img width="200" alt="Screenshot" src="https://github.com/user-attachments/assets/7b5656fa-c915-4e4f-9749-9a20e8392939">
    </td>
  </tr>
</table>
=> Feat: APP-6707 creating ocean content list component

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanContentList.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSettingsListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/extensions/compose/Extensions.kt
- Creating a SettingsListItem with all variations defined on [DS Core](https://www.figma.com/design/PgLv9k22CHHZZ867HwN65y/%F0%9F%8C%8A-Ocean-DS-Core?node-id=16032-120204&m=dev)
- Adding an extension function to draw border as divider element
<table>
  <tr>
         <img width="200" alt="Screenshot"  src="https://github.com/user-attachments/assets/21d2072c-ff0d-47b5-8c99-383a10a83197">
  </tr>
</table>
=> Feat: APP-6609 adjusting ocean setting list item component

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSettingsListItem.kt
=> feat: add optional divider

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanContentList.kt
- Necessary adjustment on component ContentListItem due missing attribute on Inverted style
[Figma](https://www.figma.com/design/PgLv9k22CHHZZ867HwN65y/%F0%9F%8C%8A-Ocean-DS-Core?node-id=15984-2078&m=dev)
<table>
  <tr>
         <img width="400" alt="Screenshot" src="https://github.com/user-attachments/assets/7ed1e312-eca4-4573-85c1-262597b25887">
    </td>
  </tr>
</table>
=> Feat: Adding new attribute on Content List Item Inverted Style

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanTransactionListItem.kt
=> feat: add limit text

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBadge.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanShortcut.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTab.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/header/OceanHeaderApp.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanTabItemModel.kt
=> feat: adjust center text

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanAlert.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanHtmlText.kt, ocean-components/src/main/java/br/com/useblu/oceands/extensions/Extensions.kt, ocean-components/src/main/res/values/strings.xml
add support html to ocean alert
=> feat: add support html

gradle/libs.versions.toml
=> feat: upgrade dependencies

app/build.gradle.kts, ocean-components/build.gradle.kts, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt, playground/build.gradle.kts
- Updates OceanInvertedTextListItem so it does not have a default background
=> feat: update OceanInvertedTextListItem modifier

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt
- Adjusted the color and font size of the title on InvertedTextListItem component.
<table>
  <tr>
         <img width="200" alt="Screenshot" src="https://github.com/user-attachments/assets/520c9dd5-24b0-4fd8-96c1-0d787ab14392">
    </td>
  </tr>
</table>
=> Fix: adjusted font size of the title and its color

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanLink.kt
- Refactor of the component OceanLink to be more generic
- Added missing Tiny style to componet
- Deprecated old OceanLink in favor to new one
<table>
  <tr>
         <img width="300" alt="Screenshot" src="https://github.com/user-attachments/assets/9c0d726f-6269-462c-80a4-de73fe178617">
    </td>
  </tr>
</table>
=> Feat: APP-7064 update ocean link

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt
=> feat: add caption to OceanInvertedTextListItem

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt
- Adjusted component InvertedTextListItem to include caption
<table>
  <tr>
         <img width="300" alt="Screenshot" src="https://github.com/user-attachments/assets/875c2169-076d-4641-8b73-b3e30307534c">
    </td>
  </tr>
</table>
=> Fix: added caption to other styles on inverted text list item

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanLink.kt
- Added missing modifier parameter to the component
=> Fix: ocean link

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanInvertedTextListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTextListItem.kt
- Added property to show/hide divider from component
- Addressed issue with font style on OceanTextListItem, style Selectable
=> Fix: adjust ocean text list

.github/dependabot.yml, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, baselineprofile/build.gradle.kts, buildSrc/src/main/kotlin/Configs.kt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
Updates Ocean to use Android API 35
=> chore: update android version

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/content/OceanCardGroup.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanTagModel.kt
Add optional OceanTag on OceanCardGroup
=> feat: add tag on card group

ocean-components/src/main/java/br/com/useblu/oceands/components/OceanSnackBar.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanToast.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanCarouselWithComponents.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanContentList.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanSettingsListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/list/OceanTransactionListItem.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanChipFilterOptions.kt
- Adds style argumentos to OceanListStyle classes
- Replace some sealed classes with sealed interfaces as no attributes were used
=> feat: add style arguments to OceanListStyle

app/src/main/java/br/com/useblu/oceands/client/ui/carousel/CarouselActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/carousel/CarouselViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanCarousel.kt
Fix: height and corner radius in Carousel
=> fix: height and corner radius in carousel

app/src/main/java/br/com/useblu/oceands/client/ui/chips/ChipsViewModel.kt, ocean-components/src/main/java/br/com/useblu/oceands/adapter/OceanChipListAdapter.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanBottomSheetCompose.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/OceanDateRangeSelectFilterSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanChip.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/daterangefilter/OceanDateRangeSelectFilterEvent.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/daterangefilter/OceanDateRangeSelectFilterSheet.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/daterangefilter/OceanDateRangeSelectFilterUIState.kt, ocean-components/src/main/java/br/com/useblu/oceands/extensions/StringExtensions.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanChip.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/OceanFilterChipBottomSheet.kt, ocean-components/src/main/res/values/strings.xml
Update OceanFilterChip to allow set custom BottomSheets without need update current usages. Also, implements common Date Range Selection with date validations
DateRangeSelect:
https://github.com/user-attachments/assets/051c3d6f-0142-49d1-ac83-f903890a419d
Custom:
https://github.com/user-attachments/assets/0a42e945-177a-46df-b257-9e8c1518eb59
=> Feat: Date Range Selection + Custom BottomSheet for OceanFilterChip

app/src/main/AndroidManifest.xml, app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/onboarding/OceanOnboardingPagerActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanOnboarding.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/OceanOnboardingPageModel.kt
- Adds possibility of caption to Onboarding Pages
- Add Onboarding Example on App
https://github.com/user-attachments/assets/5c209beb-57a7-4e15-b61f-e04f9bb87675
=> Feat: Onboarding with Caption

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanAlert.kt
Add spacing between label and button in OceanAlert WithIcon
=> Fix: Add OceanAlert WithAction Spacing

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/chart/OceanChartCard.kt
- Create loading state for OceanChartCard
=> feat: create ocean chart card skeleton

buildSrc/src/main/kotlin/Configs.kt, ocean-components/build.gradle.kts
fix: set maven publishing in build.gradle.kts
=> fix: set maven publishing in build.gradle.kts

app/src/main/java/br/com/useblu/oceands/client/ui/home/HomeActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanDatePickerDialog.kt
Add possibility to insert a Info Title and Message to OceanDatePickerDialog
=> Feat: Add Info title and message to OceanDatePickerDialog

app/src/main/java/br/com/useblu/oceands/client/ui/pinpad/PinPadActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/OceanPinPad.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/OceanPinPadHandler.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/OceanPinPadUIState.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/handlers/currency/OceanCurrencyPinPadHandler.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/handlers/password/OceanPasswordPinPadHandler.kt
Remove composable context to getResult method to be used in all contexts
https://github.com/user-attachments/assets/da2c50cd-3ad2-47d8-8c69-035d5205964c
=> Fix: Update PinPadHandler result without Composable context

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTransactionFooter.kt
Adicionando parametro opcional ao componente TransactionFooter
=> feat: add parameter to transaction footer

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/chart/OceanChartCard.kt
Fix chart legend spacing when theres no divider and title
=> fix: chart legend spacing

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/OceanPinPad.kt, ocean-components/src/main/java/br/com/useblu/oceands/ui/compose/OceanTextStyle.kt
=> Feat: Update pinpad token

app/src/main/java/br/com/useblu/oceands/client/ui/bottomnavigation/BottomNavigationActivity.kt, app/src/main/java/br/com/useblu/oceands/client/ui/bottomnavigation/BottomNavigationViewModel.kt, app/src/main/res/layout/activity_bottom_navigation.xml, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomNavigation.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanText.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/OceanPinPad.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/OceanPinPadhapticsDelegate.kt, ocean-components/src/main/java/br/com/useblu/oceands/extensions/compose/Modifiers.kt, ocean-components/src/main/java/br/com/useblu/oceands/model/compose/bottomnavigation/OceanBottomNavigationSpacingStyle.kt
Add Compact BottomNavigation + Update PinPad resize + adjustments + PinPad Haptics delegate
https://github.com/user-attachments/assets/54716a72-9ebc-4e73-92bb-1912410f4465
https://github.com/user-attachments/assets/39cb525d-4cdd-4106-9666-acc61b26ca1a
=> Feat: Compact OceanBottomNavigation

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanAccordion.kt
Essa PR substitui o uso do Text do Material 3 pelo OceanText que possui uma extensão para usar AnnotedString
https://github.com/user-attachments/assets/1659afa0-6b4b-4eca-9cbd-d2d9411c25f9
=> Fix Description Accordion

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanBottomSheet.kt
Adicionando parametro ao Bottom Sheet para controlar se ele será fechado com clique dos botoes
=> fix: add parameter to dismiss bottomsheet on button click

app/src/main/java/br/com/useblu/oceands/client/ui/pinpad/PinPadActivity.kt, ocean-components/src/main/java/br/com/useblu/oceands/components/compose/pinpad/handlers/currency/OceanCurrencyPinPadHandler.kt
Make possible to add test value to currency pinpad validation
https://github.com/user-attachments/assets/a44b4cec-f279-4519-ab90-b8702ad84e22
=> Feat: Currency Pinpad With Test Value

ocean-components/src/main/java/br/com/useblu/oceands/components/compose/OceanTopBarInverse.kt
Adicionando parametro de background color na top bar
=> feat: add background color parameter to topbar component

ocean-components/src/main/java/br/com/useblu/oceands/components/OceanAnnotatedText.kt
Add OceanAnnotatedText component to make more easily to handle with multiple styles texts and partial clickable links
Usage:
=> Feat: Add OceanAnnotatedText
